name: Integration Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v3
      - run: sudo apt update
      - run: sudo apt install -y clang cmake debhelper libblkid-dev libglib2.0-dev libgtk-3-dev liblzma-dev network-manager ninja-build packagekit pkg-config polkitd xvfb

      - name: Build test deb
        working-directory: packages/app_center/integration_test/assets/appcenter-testdeb-1.0
        run: dpkg-buildpackage

      - name: Flutter version
        run: flutter --version

      - name: Run melos generate
        run: melos generate

      - name: Run melos gen-l10n
        run: melos gen-l10n

      - name: Run integration tests
        run: |
          cd packages/app_center && \
          sudo cp integration_test/assets/packagekit-ci.pkla /var/lib/polkit-1/localauthority/50-local.d/
          sudo cp integration_test/assets/snapd-ci.pkla /var/lib/polkit-1/localauthority/50-local.d/
          LANG=en_US.UTF-8 xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' \
          flutter test integration_test
